CONNECT INTERNAL; 
CREATE USER metadata IDENTIFIED BY metadata1 DEFAULT TABLESPACE users 
TEMPORARY TABLESPACE temp PROFILE default QUOTA UNLIMITED ON users 
QUOTA UNLIMITED ON temp;
COMMIT;
GRANT CONNECT TO METADATA;
COMMIT;
DISCONNECT;
