CREATE  SCHEMA "METADATA";


CREATE TABLE "METADATA"."SCHEMAS" (
        "EXTENT" VARCHAR (16) NOT NULL,
        "DESCRIP" VARCHAR (64),
        "OWNER" VARCHAR (32),
        "NTABS" NUMERIC(4)
);

CREATE TABLE "METADATA"."TABLES" (
        "SCH" VARCHAR (16) NOT NULL,
        "EXTENT" VARCHAR (16) NOT NULL,
        "ORD" NUMERIC(4),
        "DESCRIP" VARCHAR (128),
        "NFLDS" NUMERIC(4),
        "NINDS" NUMERIC(4),
        "MAXRECORDS" NUMERIC(4),
        "UNVECTABLE" NUMERIC(4) DEFAULT 0
);

CREATE TABLE "METADATA"."TABMEMBERS" (
        "SCH" VARCHAR (16) NOT NULL,
        "EXTENT" VARCHAR (16) NOT NULL,
        "ID" NUMERIC(5) NOT NULL,
        "NAME" VARCHAR (32),
        "DESCRIP" VARCHAR (64),
        "DIM" NUMERIC(4),
        "LEN" NUMERIC(4),
        "SCALE" NUMERIC(4),
        "TY" NUMERIC(4),
        "SQLTY" NUMERIC(4),
        "TYPENAME" VARCHAR (32),
        "NOTNULL" BOOL,
        "DEFLT" VARCHAR (128),
        "MASKATTR" VARCHAR (128),
        "CHK" VARCHAR (128),
        "CHKDIGIT" VARCHAR (1),
        "INPKEY" BOOL,
	"STAMPFLD" NUMERIC(4),
        "NULLIS" VARCHAR(32)
);

CREATE TABLE "METADATA"."INDICES" (
        "SCH"  VARCHAR (16) NOT NULL,
        "EXTENT" VARCHAR (16) NOT NULL,
        "ID" NUMERIC(5) NOT NULL,
        "NAME" VARCHAR (32),
        "NFLDS" NUMERIC(4),
        "UNIQUEATTR" BOOL,
        "HASUQPHYSIND" BOOL
);

CREATE TABLE "METADATA"."INDEXATTR" (
        "SCH" VARCHAR (16) NOT NULL,
        "EXTENT" VARCHAR (16) NOT NULL,
        "INDEXID" NUMERIC(5) NOT NULL,
        "ID" NUMERIC(5) NOT NULL,
        "NAME" VARCHAR (32),
        "ATTRID" NUMERIC(5),
        "FLAGS" NUMERIC(4),
        "OFFSET" NUMERIC(4),
        "LEN" NUMERIC(4)
);

CREATE TABLE "METADATA"."REFERENCES" (
        "SCH" VARCHAR (16) NOT NULL,
        "EXTENT" VARCHAR (16) NOT NULL,
        "FLDID" NUMERIC(5) NOT NULL,
        "TY" NUMERIC(4),
        "TTABLENAME" VARCHAR (16),
        "TINDEXNAME" VARCHAR (32),
        "ISNEG" NUMERIC(4),
        "INDID" NUMERIC(5)
);

CREATE TABLE "METADATA"."REFATTRS" (
        "SCH" VARCHAR (16) NOT NULL,
        "EXTENT" VARCHAR (16) NOT NULL,
        "FLDID" NUMERIC(5) NOT NULL,
	"ID" NUMERIC(5) NOT NULL,
        "ISKEY" BOOL NOT NULL,
        "ISCONST" BOOL,
        "VALUE" VARCHAR (128)
);

CREATE TABLE "METADATA"."ENUMS" (
        "SCH" VARCHAR (16) NOT NULL,
        "NAME" VARCHAR (32) NOT NULL,
        "DESCRIP" VARCHAR (64)
);

CREATE TABLE "METADATA"."ENUMATTRS" (
        "SCH" VARCHAR (16) NOT NULL,
        "ENUMNAME" VARCHAR (32)NOT NULL,
        "ID" NUMERIC(5) NOT NULL,
        "VALUE" NUMERIC(4),
        "DESCRIP" VARCHAR (32)
);

CREATE TABLE "METADATA"."SCHPERMS" (
        "SCH" VARCHAR (16) NOT NULL,
        "UORG" BOOL NOT NULL,
        "USRGRP" NUMERIC(4)  NOT NULL,
        "PERM" NUMERIC(4) NOT NULL
);

CREATE TABLE "METADATA"."TABPERMS" (
        "SCH" VARCHAR (16) NOT NULL,
        "EXTENT" VARCHAR (16) NOT NULL,
        "UORG" BOOL NOT NULL,
        "USRGRP" NUMERIC(4) NOT NULL,
        "PERM" NUMERIC(4) NOT NULL
);

ALTER TABLE "METADATA"."SCHEMAS" ADD PRIMARY KEY ("EXTENT");
ALTER TABLE "METADATA"."TABLES" ADD PRiMARY KEY ("SCH" ,"EXTENT");
ALTER TABLE "METADATA"."TABLES" ADD FOREIGN KEY ("SCH" ) REFERENCES "METADATA"."SCHEMAS"("EXTENT");
ALTER TABLE "METADATA"."TABMEMBERS" ADD PRIMARY KEY ("SCH" ,"EXTENT","ID");
ALTER TABLE "METADATA"."TABMEMBERS" ADD FOREIGN KEY ("SCH" ,"EXTENT") REFERENCES "METADATA"."TABLES" ("SCH" ,"EXTENT");
ALTER TABLE "METADATA"."INDICES" ADD PRIMARY KEY ("SCH" ,"EXTENT","ID");
ALTER TABLE "METADATA"."INDICES" ADD FOREIGN KEY ("SCH" ,"EXTENT") REFERENCES "METADATA"."TABLES" ("SCH" ,"EXTENT");
ALTER TABLE "METADATA"."INDEXATTR" ADD PRIMARY KEY ("SCH" ,"EXTENT","INDEXID","ID");
ALTER TABLE "METADATA"."INDEXATTR" ADD FOREIGN KEY ("SCH" ,"EXTENT","INDEXID") REFERENCES "METADATA"."INDICES" ("SCH" ,"EXTENT","ID");
ALTER TABLE "METADATA"."REFERENCES" ADD PRIMARY KEY ("SCH" ,"EXTENT","FLDID");

ALTER TABLE "METADATA"."REFERENCES" ADD FOREIGN KEY ("SCH" ,"EXTENT") REFERENCES "METADATA"."TABLES" ("SCH" ,"EXTENT");
ALTER TABLE "METADATA"."REFATTRS" ADD PRIMARY KEY ("SCH" ,"EXTENT","FLDID","ID","ISKEY");
ALTER TABLE "METADATA"."REFATTRS" ADD FOREIGN KEY ("SCH" ,"EXTENT","FLDID") REFERENCES "METADATA"."REFERENCES" ("SCH" ,"EXTENT","FLDID");
ALTER TABLE "METADATA"."ENUMS" ADD PRIMARY KEY ("SCH" ,"NAME");
ALTER TABLE "METADATA"."ENUMS" ADD FOREIGN KEY ("SCH" ) REFERENCES "METADATA"."SCHEMAS" ("EXTENT");
ALTER TABLE "METADATA"."ENUMATTRS" ADD PRIMARY KEY ("SCH" ,"ENUMNAME","ID");
ALTER TABLE "METADATA"."ENUMATTRS" ADD FOREIGN KEY ("SCH" ,"ENUMNAME") REFERENCES "METADATA"."ENUMS" ("SCH" ,"NAME");
ALTER TABLE "METADATA"."SCHPERMS" ADD PRIMARY KEY ("SCH" ,"UORG","USRGRP","PERM");
ALTER TABLE "METADATA"."SCHPERMS" ADD FOREIGN KEY ("SCH" ) REFERENCES "METADATA"."SCHEMAS" ("EXTENT");
ALTER TABLE "METADATA"."TABPERMS" ADD PRIMARY KEY ("SCH" ,"EXTENT","UORG","USRGRP","PERM");
ALTER TABLE "METADATA"."TABPERMS" ADD FOREIGN KEY ("SCH" ,"EXTENT") REFERENCES "METADATA"."TABLES" ("SCH","EXTENT");

GRANT SELECT ON "METADATA"."SCHEMAS" TO PUBLIC;
GRANT SELECT ON "METADATA"."TABLES" TO PUBLIC;
GRANT SELECT ON "METADATA"."TABMEMBERS" TO PUBLIC;
GRANT SELECT ON "METADATA"."INDICES" TO PUBLIC;
GRANT SELECT ON "METADATA"."INDEXATTR" TO PUBLIC;
GRANT SELECT ON "METADATA"."REFERENCES" TO PUBLIC;
GRANT SELECT ON "METADATA"."REFATTRS" TO PUBLIC;
GRANT SELECT ON "METADATA"."ENUMS" TO PUBLIC;
GRANT SELECT ON "METADATA"."ENUMATTRS" TO PUBLIC;
GRANT SELECT ON "METADATA"."SCHPERMS" TO PUBLIC;
GRANT SELECT ON "METADATA"."TABPERMS" TO PUBLIC;

