/*
//
// WARNING: Do not edit this file!
// It was automatically generated by the 'ixgen' utility
// from the 'iddebug.gen' file.
//
*/

#include <ifound.h>
#include <ifound/iddebug.h>

extern "C" const char *tr_id_to_name(unsigned int id, void *m)
{
#ifdef ISDEBUG

	switch (id) {
	case DataBase_id:
		return "DataBase";
		break;
	case DataBaseImplem_id:
		return "DataBaseImplem";
		break;
	case DataBaseRep_id:
		return "DataBaseRep";
		break;
	case DbCursor_id:
		return "DbCursor";
		break;
	case DbCursorImplem_id:
		return "DbCursorImplem";
		break;
	case DbCursorRep_id:
		return "DbCursorRep";
		break;
	case DbIndex_id:
		return "DbIndex";
		break;
	case DbIndexImplem_id:
		return "DbIndexImplem";
		break;
	case DbIndexPart_id:
		return "DbIndexPart";
		break;
	case DbMemberType_id:
		return "DbMemberType";
		break;
	case DbObject_id:
		return "DbObject";
		break;
	case DbObjectRep_id:
		return "DbObjectRep";
		break;
	case DbSet_id:
		return "DbSet";
		break;
	case DbSetImplem_id:
		return "DbSetImplem";
		break;
	case DbSetRep_id:
		return "DbSetRep";
		break;
	case DbTypeDescr_id:
		return "DbTypeDescr";
		break;
	case FmFieldRep_id:
		return "FmFieldRep";
		break;
	case FormRep_id:
		return "FormRep";
		break;
	case GridColumn_id:
		return "GridColumn";
		break;
	case GridDev_id:
		return "GridDev";
		break;
	case GridRep_id:
		return "GridRep";
		break;
	case RegExp_id:
		return "RegExp";
		break;
	case ReportRep_id:
		return "ReportRep";
		break;
	case Resource_id:
		return "Resource";
		break;
	case RpAccumulator_id:
		return "RpAccumulator";
		break;
	case RpFieldRep_id:
		return "RpFieldRep";
		break;
	case RpZoneObject_id:
		return "RpZoneObject";
		break;
	case RpZoneRep_id:
		return "RpZoneRep";
		break;
	case VirtualFile_id:
		return "VirtualFile";
		break;
	case srep_id:
		return "srep";
		break;
	case BlockedFile_id:
		return "BlockedFile";
		break;
	case CacheBuffer_id:
		return "CacheBuffer";
		break;
	case Client_id:
		return "Client";
		break;
	case Coroutine_id:
		return "Coroutine";
		break;
	case GServObj_id:
		return "GServObj";
		break;
	case IndexNode_id:
		return "IndexNode";
		break;
	case Journal_id:
		return "Journal";
		break;
	case LockObject_id:
		return "LockObject";
		break;
	case NotifyLock_id:
		return "NotifyLock";
		break;
	case RunLog_id:
		return "RunLog";
		break;
	case SvConfigFile_id:
		return "SvConfigFile";
		break;
	case SvConnection_id:
		return "SvConnection";
		break;
	case SvExpr_id:
		return "SvExpr";
		break;
	case SvField_id:
		return "SvField";
		break;
	case SvInList_id:
		return "SvInList";
		break;
	case SvIndFld_id:
		return "SvIndFld";
		break;
	case SvIntegrity_id:
		return "SvIntegrity";
		break;
	case Transaction_id:
		return "Transaction";
		break;
	case CmdHistory_id:
		return "CmdHistory";
		break;
	case DaliCmd_id:
		return "DaliCmd";
		break;
	case Gamut_id:
		return "Gamut";
		break;
	case GenericCanvas_id:
		return "GenericCanvas";
		break;
	case GenericPanel_id:
		return "GenericPanel";
		break;
	case LoadedThing_id:
		return "LoadedThing";
		break;
	case Site_id:
		return "Site";
		break;
	case TagIndex_id:
		return "TagIndex";
		break;
	case Thing_id:
		return "Thing";
		break;
	case View_id:
		return "View";
		break;
	case ViewManager_id:
		return "ViewManager";
		break;
	case Command_id:
		return "Command";
		break;
	case DaliAttributeZones_id:
		return "DaliAttributeZones";
		break;
	case DaliRc_id:
		return "DaliRc";
		break;
	case DaliText_id:
		return "DaliText";
		break;
	case DaliTextCursor_id:
		return "DaliTextCursor";
		break;
	case DaliView_id:
		return "DaliView";
		break;
	case History_id:
		return "History";
		break;
	case AttributeZones_id:
		return "AttributeZones";
		break;
	case Desktop_id:
		return "Desktop";
		break;
	case Log_id:
		return "Log";
		break;
	case LogItem_id:
		return "LogItem";
		break;
	case MenuItem_id:
		return "MenuItem";
		break;
	case StrHistory_id:
		return "StrHistory";
		break;
	case Text_id:
		return "Text";
		break;
	case TextCursor_id:
		return "TextCursor";
		break;
	case WinApp_id:
		return "WinApp";
		break;
	case WinCmd_id:
		return "WinCmd";
		break;
	case WinObj_id:
		return "WinObj";
		break;
	case WinObjAct_id:
		return "WinObjAct";
		break;
	case Window_id:
		return "Window";
		break;
	case BaseAction_id:
		return "BaseAction";
		break;
	case BuildUnit_id:
		return "BuildUnit";
		break;
	case EntryAttributes_id:
		return "EntryAttributes";
		break;
	case IbExpr_id:
		return "IbExpr";
		break;
	case IbSource_id:
		return "IbSource";
		break;
	case ib_id:
		return "ib";
		break;
	case StampFile_id:
		return "StampFile";
		break;
	case TableEntry_id:
		return "TableEntry";
		break;
	case Table_id:
		return "Table";
		break;
	case UnitRep_id:
		return "UnitRep";
		break;
	}
#endif
	return "Unknown!";
}
