/*
//
// WARNING: Do not edit this file!
// It was automatically generated by the 'ixgen' utility
// from the 'iddebug.gen' file.
//
*/

#ifndef IDDEBUG_H
#define IDDEBUG_H

#ifdef ISDEBUG

#define DataBase_id 0x796ffffe
#define DataBaseImplem_id 0x796ffffd
#define DataBaseRep_id 0x796ffffc
#define DbCursor_id 0x796ffffb
#define DbCursorImplem_id 0x796ffffa
#define DbCursorRep_id 0x796ffff9
#define DbIndex_id 0x796ffff8
#define DbIndexImplem_id 0x796ffff7
#define DbIndexPart_id 0x796ffff6
#define DbMemberType_id 0x796ffff5
#define DbObject_id 0x796ffff4
#define DbObjectRep_id 0x796ffff3
#define DbSet_id 0x796ffff2
#define DbSetImplem_id 0x796ffff1
#define DbSetRep_id 0x796ffff0
#define DbTypeDescr_id 0x796fffef
#define FmFieldRep_id 0x796fffee
#define FormRep_id 0x796fffed
#define GridColumn_id 0x796fffec
#define GridDev_id 0x796fffeb
#define GridRep_id 0x796fffea
#define RegExp_id 0x796fffe9
#define ReportRep_id 0x796fffe8
#define Resource_id 0x796fffe7
#define RpAccumulator_id 0x796fffe6
#define RpFieldRep_id 0x796fffe5
#define RpZoneObject_id 0x796fffe4
#define RpZoneRep_id 0x796fffe3
#define VirtualFile_id 0x796fffe2
#define srep_id 0x796fffe1
#define BlockedFile_id 0x796fffe0
#define CacheBuffer_id 0x796fffdf
#define Client_id 0x796fffde
#define Coroutine_id 0x796fffdd
#define GServObj_id 0x796fffdc
#define IndexNode_id 0x796fffdb
#define Journal_id 0x796fffda
#define LockObject_id 0x796fffd9
#define NotifyLock_id 0x796fffd8
#define RunLog_id 0x796fffd7
#define SvConfigFile_id 0x796fffd6
#define SvConnection_id 0x796fffd5
#define SvExpr_id 0x796fffd4
#define SvField_id 0x796fffd3
#define SvInList_id 0x796fffd2
#define SvIndFld_id 0x796fffd1
#define SvIntegrity_id 0x796fffd0
#define Transaction_id 0x796fffcf
#define CmdHistory_id 0x796fffce
#define DaliCmd_id 0x796fffcd
#define Gamut_id 0x796fffcc
#define GenericCanvas_id 0x796fffcb
#define GenericPanel_id 0x796fffca
#define LoadedThing_id 0x796fffc9
#define Site_id 0x796fffc8
#define TagIndex_id 0x796fffc7
#define Thing_id 0x796fffc6
#define View_id 0x796fffc5
#define ViewManager_id 0x796fffc4
#define Command_id 0x796fffc3
#define DaliAttributeZones_id 0x796fffc2
#define DaliRc_id 0x796fffc1
#define DaliText_id 0x796fffc0
#define DaliTextCursor_id 0x796fffbf
#define DaliView_id 0x796fffbe
#define History_id 0x796fffbd
#define AttributeZones_id 0x796fffbc
#define Desktop_id 0x796fffbb
#define Log_id 0x796fffba
#define LogItem_id 0x796fffb9
#define MenuItem_id 0x796fffb8
#define StrHistory_id 0x796fffb7
#define Text_id 0x796fffb6
#define TextCursor_id 0x796fffb5
#define WinApp_id 0x796fffb4
#define WinCmd_id 0x796fffb3
#define WinObj_id 0x796fffb2
#define WinObjAct_id 0x796fffb1
#define Window_id 0x796fffb0
#define BaseAction_id 0x796fffaf
#define BuildUnit_id 0x796fffae
#define EntryAttributes_id 0x796fffad
#define IbExpr_id 0x796fffac
#define IbSource_id 0x796fffab
#define ib_id 0x796fffaa
#define StampFile_id 0x796fffa9
#define TableEntry_id 0x796fffa8
#define Table_id 0x796fffa7
#define UnitRep_id 0x796fffa6
#define Pane_id 0x796fffa5
#define Value_id 0x796fffa4

#endif

#endif
